[package]
name = "ibkr-toy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
derive_more = "0.99"
itertools = "0.10"
mockall = "0.11"
mockall_double = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"