name: verify
on:
  - push
  - pull_request
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache Rust
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            target
            target-install
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: actions/cache@v3
        name: Cache NPM
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
      - uses: actions/setup-node@v4
        with:
          node-version: 21.6.1
      - run: npm install --global prettier
      - run: cargo install --git https://github.com/seamlik/devops.git --force
        env:
          CARGO_TARGET_DIR: target-install
      - run: devops format
      - run: git --no-pager diff --exit-code
      - run: cargo test
