on:
  - push
  - pull_request
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: seamlik/devops/.github/actions/cache-nodejs@master
      - run: npm install --global prettier
      - uses: seamlik/devops/.github/actions/install-devops@master

      # Verify
      - uses: seamlik/devops/.github/actions/upload-codecov@master
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: devops format rust markdown yaml
      - uses: seamlik/devops/.github/actions/check-formatting@master
